scriptname byohbuildingobjectinteriorscript extends byohbuildingobjectscript
event oncontainerchanged(objectreference aknewcontainer, objectreference akoldcontainer)
endevent
;This file was cleaned with PapyrusSourceHeadliner 1